### ISSUE TITLE
Can you explain what pattern is meant ?

### ISSUE THREAD

**Issue by gkumar9** [timdp/metalsmith-discover-partials#9]
I will explain my directory, and how i intend to use your plugin.

**_src_**: is the directory of index.html file.
content:
```
---
layout: layout1.html
---

<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.</h2>
```
Now,

_**layouts**_: is the directory where i store my layout file which is used my index.html file
content: layout1.layout
```
{{> Header }}

{{{ contents }}}

{{> Footer }}
```
Further,
_**partials**_: my partial directory where Header and footer files are stored.This is inside layout directory.

my metalsmith config file:index.js
content:
```
var Metalsmith  = require('metalsmith');
var markdown    = require('metalsmith-markdown');
var layouts     = require('metalsmith-layouts');
var fs =require('fs');
var Handlebars = require('handlebars');
var inPlace = require('metalsmith-in-place')
var discoverPartials = require('metalsmith-discover-partials')

Metalsmith(__dirname)
  .metadata({
    generator: "Metalsmith",
    url: "http://www.metalsmith.io/"
  })
  .source('./src')
  .destination('./build')
  .clean(true)
  .use(markdown())
  .use(inPlace(true))
  .use(layouts({
    engine: 'handlebars'
  }))
  .use(discoverPartials({
    directory: './layouts/partials',
    // pattern: /\.html$/ // What is pattern and i should use it for my handlebar syntax:{{> header }} file
  }))
  .build(function(err, files) {
    if (err) { throw err; }
  });

```
Now, you understand my directory structure and index.js file. How could I use your plugin so it automatically detects the required partials and registers them?

**Comment by timdp** [comment]
The `pattern` option just tells `discoverPartials()` which files to consider. In your case, if you had the following partials under `layouts/partials/`:

```
layouts/partials/
  partial1.html
  partial2.hbs
  partial3.txt
  partial4.html
```

the regular expression `/\.html$/` would only accept files whose name ends with `.html`, so it would discover `partial1` and `partial4`.

**Comment by gkumar9** [comment]
OK. So, if I use ```/\.html$/``` it will register all .html files in metalsmith js file right ?

like this:
```
 Handlebars.registerPartial('Header', fs.readFileSync(__dirname + '/layouts/partials/partial1.html').toString());
 Handlebars.registerPartial('Footer', fs.readFileSync(__dirname + '/layouts/partials/partial4.html').toString());
```

**Comment by timdp** [comment]
Yes, that's pretty much the idea, except that the names won't be `Header` and `Footer`.

**Comment by gkumar9** [comment]
Then, how is it registering? Because as you know the registered name should be same as the name of partial we are using in layout otherwise an error is thrown.

**Comment by timdp** [comment]
Just the basename of the file. For example, `partial4`.

**Comment by gkumar9** [comment]
So, I changed my layout file to : 
```
{{> header2 }}
{{{ contents }}}
{{> footer3 }}
```
and these two files header2 and footer3 are in my partial folder.
But still it showed me this error
```
/home/software/workspace/metalsmith/examples/static-site/index.js:43
    if (err) { throw err; }
               ^
Error: The partial header2 could not be found
    at Object.invokePartial (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:281:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval [as main] (eval at createFunctionContext (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
    at main (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/home/software/workspace/metalsmith/examples/static-site/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at /home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:735:16
    at /home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:144:5
    at Promise._execute (/home/software/workspace/metalsmith/examples/static-site/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/software/workspace/metalsmith/examples/static-site/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/software/workspace/metalsmith/examples/static-site/node_modules/bluebird/js/release/promise.js:79:10)
    at promisify (/home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:137:10)
    at Function.exports.handlebars.render (/home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:725:10)
    at /home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:165:27
    at /home/software/workspace/metalsmith/examples/static-site/node_modules/consolidate/lib/consolidate.js:99:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
```

**Comment by timdp** [comment]
You could open `node_modules/metalsmith-discover-partials/index.js` and insert a `console.log()` right before the call to `Handlebars.registerPartial()` to verify that it's picking up the partial and check how it's registering it.
